### ISSUE TITLE
Unable to configure plugin

### ISSUE THREAD

**Issue by AlexKucera** [joshp23/YOURLS-Snapshot#9]
When I try to go to the configuration page of the plugin I am presented with an empty page.

Any ideas what might be wrong or how I could diagnose it?

![](http://babylondreams.de/shared/Screen-Shot-2017-09-04-at-11.29.58-ntTg/Screen-Shot-2017-09-04-at-11.29.58.png)

**Comment by joshp23** [comment]
I would start by checking permissions, turning on debug mode if it isn't already, checking the PHP error reporting level and then looking in the logs.

**Comment by AlexKucera** [comment]
It was the Cache folder. The plugin couldn't create it, but it didn't give me any warning but failed silently instead.

I have a new problem now. I get a preview page and it renders the preview image correctly (in the cache folder), however on the page I get a broken image link.

![](http://babylondreams.de/shared/Screen-Shot-2017-09-04-at-17.09.05-ttB9/Screen-Shot-2017-09-04-at-17.09.05.png)

**Comment by AlexKucera** [comment]
Got it. It didn't like my symlinking the srv.php. I copied it instead and now everything works.

**Comment by joshp23** [comment]
I added in a simple warning to address this issue. I think I will rewrite so that the cache is not automatically created, but setup is checked, and then option is exposed to create it via the admin interface. Thanks.
